TDD project
gitbygaurav/TDD-Project pull request #1
Opened 2023-03-16 13:03 UTC by PrantoshB

2023-03-16 13:45 UTC, Kamba56 requested changes
Hi @PrantoshB, @gauravgangwarweb , 

Good job so far!!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏!👏👏👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- [x] Great use of Git workflow!👏👏👏
- [x] All linters passed
- [x] Great job using TDD to implement the solver class.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-16 13:45 UTC, Kamba56 commented on solver.rb
> +      'Plese give me a positive number'
- [ ] As demanded by the project requirements, kindly make this method raise an exception error if the number is negative. Also, test for the error raised.

you can use;
```ruby
if number.negative?
  raise Exception
```

2023-03-16 13:45 UTC, Kamba56 commented on spec/solver_spec.rb
> +      it 'returns 1 if number is equal to 1' do
- [Optional] Kindly correct the description of this `it` block. The description should describe what the block is testing. You can use something like;
`it 'Should return number if the number is not divisible by 3 or 5'`.

2023-03-17 06:14 UTC, PrantoshB commented
Thanks @Kamba56 for the suggestions.

We have implemented the changes and submitting for next review.

2023-03-17 06:44 UTC, Qoosim approved these changes
#  *Status: Approved* :tada: :heavy_check_mark: 

Hi @team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct Git Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966)

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-17 06:48 UTC, gauravgangwarweb commented
Hii @Qoosim 👋

Thanks for approving our PR.

2023-03-17 06:48 UTC, merged

2023-03-17 07:11 UTC, Qoosim commented
Hey @gauravgangwarweb, you're most welcome brother. :handshake:

2023-03-17 07:44 UTC, Kamba56 commented
> Thanks @Kamba56 for the suggestions.
> 
> We have implemented the changes and submitting for next review.

You are welcome, happy coding 😁💪🏾